# Generated by Django 5.0.6 on 2024-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
